name: Update manifest

permissions:
    contents: write # Required to push changes

on:
    # Runs every three hours, on the hour
    schedule:
        - cron: "0 */3 * * *"
    # Allow manual triggering
    workflow_dispatch:

jobs:
    update-manifest:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: "refs/heads/manifest-update"
                  fetch-depth: 0

            - name: Set up Python 3.12 (with pip cache)
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12" # 'pyaudioop' removed in 3.13
                  cache: "pip"

            - name: Cache pip dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run update_manifest.py
              id: run_script
              run: |
                  python update_manifest.py
                  echo "exit_code=$?" >> $GITHUB_OUTPUT

            - name: Warn if up-to-date
              if: steps.run_script.outputs.exit_code == 1
              run: |
                  echo "Warning: Local manifest is up-to-date."
                  exit 0

            - name: Commit changes
              if: steps.run_script.outputs.exit_code == 0
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email ""
                  git add manifests/
                  REV_NUMBER="$(cat manifests/LATEST_REVISION)"
                  git commit -m "Update mobile manifest to revision v$REV_NUMBER"
                  git push origin manifest-update
